package org.jpmml.manager;

import java.util.*;

import org.dmg.pmml.*;

/**
 * 
 * This class allows to handle the Scorecard model in a simpler way
 * than the scorecard class generated by the parser.
 *  
 * @author tbadie
 *
 */
/**
 * @author tbadie
 *
 */
public class ScoreCardModelManager extends ModelManager<Scorecard> {
	protected Scorecard scorecard = null;

	public ScoreCardModelManager(){
	}

	public ScoreCardModelManager(PMML pmml){
		this(pmml, find(pmml.getContent(), Scorecard.class));
	}

	public ScoreCardModelManager(PMML pmml, Scorecard scorecard){
		super(pmml);

		this.scorecard = scorecard;
	}

	public String getSummary(){
		return "Scorecard";
	}

	@Override
	public Scorecard getModel(){
		ensureNotNull(this.scorecard);

		return this.scorecard;
	}

	public Scorecard createClassificationModel(){
		return createModel(MiningFunctionType.CLASSIFICATION);
	}

	/**
	 * @throws ModelManagerException If the Model already exists
	 *
	 * @see #getModel()
	 */
	public Scorecard createModel(MiningFunctionType miningFunction){
		ensureNull(scorecard);

		scorecard = new Scorecard(new MiningSchema(),
								new Characteristics(), miningFunction);

		List<Model> content = getPmml().getContent();
		content.add(scorecard);

		return scorecard;
	}

	/**
	 * The list of characteristic of the scorecard. Characteristic
	 *  includes the reason code, the list of attributes, the baseline score.
	 * 
	 * @return The characteristics.
	 */
	public Characteristics getCharacteristics() {
		ensureNotNull(scorecard);
		
		return scorecard.getCharacteristics();
	}
	
	/**
	 * Get a particular characteristic.
	 * 
	 * @param name The characteristic we want to get.
	 * @return The wanted characteristic, or null if there is no such 
	 * characteristic.
	 */
	public Characteristic getCharacteristic(String name) {
		ensureNotNull(scorecard);
		
		List<Characteristic> l = scorecard.getCharacteristics().getCharacteristics();
		for (Characteristic c : l) {
			if (c.getName().equals(name)) {
				return c;
			}
		}

		return null;
	}
}